<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-8BDV13S" failures="3" tests="3" name="Test(failed)" time="23.306" errors="0" timestamp="2024-09-23T17:11:36 IST">
  <testcase classname="testCases.TestCase3" name="DDTlogin" time="2.973">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TestCase3.DDTlogin(TestCase3.java:60)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- DDTlogin -->
  <testcase classname="testCases.TestCase3" name="DDTlogin" time="2.536">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TestCase3.DDTlogin(TestCase3.java:51)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- DDTlogin -->
  <testcase classname="testCases.TestCase3" name="DDTlogin" time="1.406">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TestCase3.DDTlogin(TestCase3.java:42)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- DDTlogin -->
</testsuite> <!-- Test(failed) -->
